### ISSUE TITLE
What about an alternative to using an email password like a fake SMTP server support instead of email ? 

### ISSUE THREAD

**Issue by minanagehsalalma** [PushpenderIndia/technowlogger#21]
Just like this
https://github.com/aydinnyunus/WifiPassword-Stealer

Also what do you think about these methods of protecting the excitable
Here
https://github.com/hawksh/Hidden-miner-builder

**Comment by Technowlogy-Pushpender** [comment]
I will think to implement those methods, and if you want to use another
SMTP server, then you have to replace the SMTP url to your custom url

Default url : smtp.google.com

Replace this url from keylogger.py and password_stealer.py

**Comment by minanagehsalalma** [comment]
> you have to replace the SMTP url to your custom url

@Technowlogy-Pushpender okay thanks ... add it to the readme too.
