### ISSUE TITLE
Virus Detected: Trojan:Script/Wacatac.B!ml

### ISSUE THREAD

**Issue by CryptoDevol** [PushpenderIndia/technowlogger#36]
Windows Defender.

This makes it useless for me. Is there a way you can figure out which feature is detected as a virus so we can remove that function.

![image](https://user-images.githubusercontent.com/79806881/110195606-e95b2b80-7e03-11eb-9c8b-9074925c73bb.png)

**Comment by PushpenderIndia** [comment]
Use your own private cryptor, open source tools can be detected very easily
