### ISSUE TITLE
technowgen.py: command not found

### ISSUE THREAD

**Issue by User-790** [PushpenderIndia/technowlogger#44]
Every single command I run this message shows, any suggestions as to what I have been doing wrong? this is my input:
 technowgen.py  -e myemailhere@gmail.com
technowgen.py: command not found. 
I am working with Linux Debian version on here and the installations for python went successful. I ran the program and the menu loaded successfully as well.
![pic](https://user-images.githubusercontent.com/90978354/172049267-cf92cbae-c679-4b52-8bb3-f52a393d1264.png)

**Comment by PushpenderIndia** [comment]
Read the documentation properly, you need to provide email password, output
file name, target os (-w or -l)

**Comment by User-790** [comment]
> Read the documentation properly, you need to provide email password, output file name, target os (-w or -l)
> […](#)

Ok thank you so much.
