### ISSUE TITLE
Less secure app access is no more

### ISSUE THREAD

**Issue by Poatri-US** [PushpenderIndia/technowlogger#47]
![image](https://user-images.githubusercontent.com/83054753/172844150-b624261e-515c-41d7-92cf-c34dbae60c47.png)

Google has turned less secure app access off , no way to obtain the logs now , perhaps you could recode it to use some other email company ? @PushpenderIndia

**Comment by PushpenderIndia** [comment]
Please read `Important` section from Readme, you can still use gmail for keylogger, you just need to use app specific password instead of gmail password

**Comment by PushpenderIndia** [comment]
I will also update the project so that, people can use any other smtp server of there choice, instead of gmail smtp

Also planning to create a php dashboard as a additional feature to receive logs instead of email
