### ISSUE TITLE
Error: 

### ISSUE THREAD

**Issue by babaoye** [PushpenderIndia/technowlogger#59]
i got this when i used the --debug tag attribute. please what does it mean

am not getting any keylog file at all tried to use other smtp apart from google after changing the keylogger default smtp and also payssword.py default smtp still no result what am i doing wrong??

![Screenshot (6)](https://user-images.githubusercontent.com/44350882/194782240-08059891-487e-4423-b018-63fefc4fa6fb.png)

**Comment by PushpenderIndia** [comment]
Which email provider you are using?

Currently stealer are only supported for gmail, and debug flag will run the
virus in foreground, this flag is helpful for debugging any issue

For gmail, create app specific password and then use that password, not the
account password

For outlook you can use the same account password

**Comment by babaoye** [comment]
the keylog doesnt go to the gmail acccount....i dont recieve the keylogs in gmail.....that was why i used https://poczta.onet.pl/
or is there some hours to wait for the payload to be active?? and i tested with the test.py the test was entering the command prompt which shows that everything is fine....but then when i try to compile the whole project for some reason it wont enter gmail.

**Comment by babaoye** [comment]
issue sorted out by changing the smtp i now recieve the mails of the payload to my gmail.
